[platformio]
default_envs = esp32-cvbs-viewer
boards_dir = ./boards
src_dir = src
lib_dir = lib

[env]
build_src_filter = +<*> -<viewer_*>
build_flags = 
	-D ARDUINO_ARCH_ESP32
	-D VIEWER_WIFI_SSID='"Akwarium-2-4"'
	-D VIEWER_WIFI_PASS='"wifi2da2875277"'
	-D VIEWER_STREAM_HOST='"192.168.50.86"'
	-D VIEWER_STREAM_PORT=80
	-D VIEWER_STREAM_PATH='"/mjpeg/1"'

[env:esp32-cvbs-viewer]
build_type = debug
platform = espressif32
framework = arduino
board = esp32dev
board_build.partitions = esp32-cvbs-viewer.csv
upload_protocol = esptool
upload_speed = 921600
monitor_speed = 115200
lib_deps =
	bitbank2/JPEGDEC@^1.6.1
lib_extra_dirs = .
lib_ldf_mode = deep+
build_src_filter = +<viewer_cvbs.cpp>
build_flags =
	-D LOG_LEVEL=6
	; -D DISABLE_LOGGING
	; -D WM_NODEBUG

